# Definition:
NumPy is a library that allows us to perform large scale mathematical scientific calculations efficiently, quicikly and flexibly.

Num-> Numerical
Py->Python
NumPy->Nummerical Python

# Range()

range(start, stop, step)

Starts from start but ends at stop-1

In [1]:
range(0,5)

range(0, 5)

In [2]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,5,2))

[0, 2, 4]

In [9]:
list1=[1,2,3,4,5]
list2=[1,2,3,4,5]
listMUX=[]
for i in range(0,len(list1)):
    listMUX.append(list1[i]*list2[i])
print(listMUX)

[1, 4, 9, 16, 25]


In [10]:
import numpy as np

In [11]:
numList1=np.array([1,2,3,4,5])
numList2=np.array([1,2,3,4,5])
print(numList1*numList2)

[ 1  4  9 16 25]


# NumPy Array()

In [17]:
import numpy as np

In [9]:
np.array([1,2,3,4,5])               #creates an array

<class 'builtin_function_or_method'>


In [4]:
list1=[1,2,3.5,4,5.1]               #list contains data in multiple data types
list1

[1, 2, 3.5, 4, 5.1]

In [5]:
print(type(list1))

<class 'list'>


In [10]:
np.array([1,2,3.5,4,5.1])            #array() contains elemets in 1 data type only

array([1. , 2. , 3.5, 4. , 5.1])

In [11]:
np.array([1,2,3.5,4,5.1],dtype="int")

array([1, 2, 3, 4, 5])

In [19]:
np.array([[1,2,3],[4,5,6]])          #Creating a two dimensional array using array() function

array([[1, 2, 3],
       [4, 5, 6]])

Conclusion: List can store data of different data types while numpy array store data of only 1 data type and to convert data in the desired data type you can use "dtype="type""

# Zeros()

In [12]:
np.zeros(5)                      #creates an array containing zero in all its elements

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5,dtype="int")

array([0, 0, 0, 0, 0])

In [14]:
np.zeros((2,2),dtype="int")

array([[0, 0],
       [0, 0]])

In [23]:
np.zeros((2,3,4),dtype="int")
#        (z,x,y)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

# Ones()

In [16]:
import numpy as np
np.ones(5)                      #creates an array containing zero in all its elements

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [21]:
np.ones((2,3,4)) #z,x,y(depth, width, height)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# Full()

In [24]:
np.full(5,1)                    
#     (size,number to be filled with)

array([1, 1, 1, 1, 1])

In [25]:
np.full((2,2),1)

array([[1, 1],
       [1, 1]])

Fills the array with the number given.

# Arange()

In [9]:
import numpy as py
print(py.arange(5,10,2,dtype="int"))
print(py.arange(0,10,dtype="int"))
#arange(start,stop, jump, type)

[5 7 9]
[0 1 2 3 4 5 6 7 8 9]


# Eye()

In [5]:
import numpy as py
print(py.eye(2,dtype="int"))
print(py.eye(3,3))
print(py.eye(3,2))
#eye(rows,columns(optional,considers same as rows if not present),type)

[[1 0]
 [0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]


# linspace()

In [9]:
import numpy as py
print(py.linspace(0,10,5))
print(py.linspace(1,10,5))
#linspace(start,stop,count=50,dtype="float",ednpoint="False")
#Divides the number from start to end(inclusive) into count "equal" parts

[ 0.   2.5  5.   7.5 10. ]
[ 1.    3.25  5.5   7.75 10.  ]


In [15]:
from numpy import *
a=linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


# arrange()      
###### (converts array from lower dimension to higher)

In [20]:
from numpy import *
array=arange(0,10)
print(array)
print(array.ndim)
array=array.reshape(5,2)
print(array)
print(array.ndim)
array=array.reshape(1,10)
print(array)
print(array.ndim)
#if requeriments are not met i.e number of elements are less or more then error is thrown

[0 1 2 3 4 5 6 7 8 9]
1
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
2
[[0 1 2 3 4 5 6 7 8 9]]
2


In [24]:
#Using arange function (to create array) with the reshape function(converting the 1D array to a 2D)
array=arange(1,7).reshape((3,2)) 
print(array)

[[1 2]
 [3 4]
 [5 6]]


# Rand()

In [12]:
import numpy as np

#Creates an array of 5 random number between 0 and 1
print(np.random.rand(5),"\n")

#Craetes an array of 5x5 of random numbers between 0 and 1(does not have to pass a tuple but pass the order)
print(np.random.rand(5,5),"\n")

#Creates an array of 5 random numbers of standard normal distribution or gaussian distribution
print(np.random.randn(5),"\n")

#Craetes an array of 5x5 of random numbers of standard normal distribution or gaussian distribution(does not have to pass a tuple but pass the order)
print(np.random.randn(5,5),"\n")

#Creates an array of 1 random number between low limit(1) and upper limit(10)[lower is inclusive while upper is exclusive]
print(np.random.randint(1,10),"\n")

#Creates an array of 6 random numbesr between low limit(1) and upper limit(10)[lower is inclusive while upper is exclusive]
randArray=np.random.randint(1,10,6)
print(randArray,"\n")
#Reshaping the 1D array to 2D using reshape() function
randArray=randArray.reshape(2,3)
print(randArray,"\n")

[0.24304013 0.16038994 0.89143968 0.06281822 0.80353123] 

[[0.06793159 0.95883089 0.26419232 0.50955753 0.47553733]
 [0.15098046 0.6063378  0.13602908 0.72958164 0.9216685 ]
 [0.69017779 0.56450621 0.29064342 0.67473115 0.99179672]
 [0.73636838 0.3322682  0.81320997 0.0442665  0.66472504]
 [0.73890378 0.12962298 0.35596908 0.39552562 0.94971035]] 

[-0.67526545 -0.64571176 -0.28411033 -1.54225397 -0.6392836 ] 

[[ 0.93022897 -0.99078342  1.12737925 -2.21408568  1.92601596]
 [-0.46653379  1.04263073 -0.56285506  0.21065255 -0.4587721 ]
 [-1.04014985  1.49488897 -0.04521789  0.10730243  0.46818656]
 [ 1.67912046  0.41275909 -0.17026422  0.3610627   1.53079058]
 [ 0.09753929  0.11205199  0.88457868  0.27738083 -0.51880261]] 

6 

[2 7 6 3 9 2] 

[[2 7 6]
 [3 9 2]] 



# .shape(), .dtype(), .ndim()

In [29]:
#.shape() function gives the order of the array
import numpy as np

array=np.arange(0,8)
print(array)
print(array.shape,"\n")

array=array.reshape(4,2)
print(array)
print(array.shape,"\n")

array=np.array([0]);
print(array)
print(array.shape,"\n")

[0 1 2 3 4 5 6 7]
(8,) 

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2) 

[0]
(1,) 



In [30]:
#.ndim() function gives the dimension of the array
import numpy as np

array=np.arange(0,8)
print(array)
print(array.ndim,"\n")

array=array.reshape(4,2)
print(array)
print(array.ndim,"\n")

array=np.array([0]);
print(array)
#.ndim() function gives the dimension of the arrayprint(array.ndim,"\n")

[0 1 2 3 4 5 6 7]
1 

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
2 

[0]
1 



In [32]:
#.ndim() function gives the data type of the array
import numpy as np

array=np.arange(0,8)
print(array)
print(array.dtype,"\n")

array=np.arange(0,8,dtype="float")
print(array)
print(array.dtype,"\n")

[0 1 2 3 4 5 6 7]
int32 

[0. 1. 2. 3. 4. 5. 6. 7.]
float64 



# max() argmax()

In [3]:
from numpy import *

In [10]:
num=random.randint(1,10,5)
print(num)
print(num.max())
print(num.argmax())

[8 2 4 9 3]
9
3


In [11]:
num=random.randint(0,50,(3,4))
print(num)
print(num.max())
print(num.argmax())

[[31  9  7  2]
 [26 41 40  0]
 [42  4  1 12]]
42
8


max() function returns the maximum value in the array while the argmax() function returns the index of the maximum value(counting starts from 0, left to right)

# min() argmin()

In [14]:
import numpy as np
num=random.randint(1,50,10)
print(num)
print(num.min())
print(num.argmin())

[28 42  9 11 45 17 12 20 28 12]
9
2


In [15]:
num=random.randint(1,50,(3,4))
print(num)
print(num.min())
print(num.argmin())

[[ 7 48  4 29]
 [ 4 49 19  6]
 [44 48 17 38]]
4
2


min() function returns the minimum value in the array while the argmin() function returns the index of the minimum value(counting starts from 0, left to right)

# Concatenate()

In [74]:
#Concatenating a 1D array:-
#concatenate([array1, array2])

from numpy import *

array1=arange(1,5)
print(array1)

array2=arange(5,9)
print(array2)

#Concatenates(joins) array1& array2
array3=concatenate([array1,array2])
print(array3)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]


In [75]:
#Concatenating a 2D array:-
#Concatenating arrays on the basis of axis:-

array1=arange(1,5).reshape(2,2)
print(array1,"\n")
array2=array([[5,6],[7,8]])
print(array2,"\n")

#if axis=0 then concatenates column wise(by default axis is 0)
array3=concatenate([array1,array2],axis=0)
print(array3,"\n")
#4x2

#if axis=1 then concatenates row wise(by default axis is 0)
array3=concatenate([array1,array2],axis=1)
print(array3,"\n")
#2x4

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]] 



# split()

In [69]:
#Splitting a 1D array:-

import numpy as np

#Splitting manually on the basis of index
array=np.array([1,2,3,4,4,5,5,5])
print(array,"\n")
(x,y,z)=np.split(array,[2,5])
print(x,"\n")
print(y,"\n")
print(z,"\n")

#Splitting on the basis of portions
(a,b,c,d)=np.split(array,4)
print(a,"\n")
print(b,"\n")
print(c,"\n")
print(d,"\n")

[1 2 3 4 4 5 5 5] 

[1 2] 

[3 4 4] 

[5 5 5] 

[1 2] 

[3 4] 

[4 5] 

[5 5] 



In [84]:
#Splitting a 2D array:-

import numpy as np

#Creating a 2D array
array=np.arange(0,20).reshape(5,4)
print(array)

#Splitting the array
np.split(array,[1,3])                      #Splits the array into 3 portions, 1st row, second and third row, 4th and 5th row

#Storring the splitted arrays into variables
x,y,z=np.split(array,[1,3])                #By default axis is taken 0(i.e rows operation)
print(x)
print(y)
print(z)

x,y,z=np.split(array,[1,3], axis=1)        #Axis is 1(i.e. columns operation)
print(x)
print(y)
print(z)

#hsplit
#vsplit

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]]
[[ 0]
 [ 4]
 [ 8]
 [12]
 [16]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]]
[[ 3]
 [ 7]
 [11]
 [15]
 [19]]


# Sort()

In [68]:
#Sorting an array:-
#sort(array, axis=by default 1(i.e sorts row wise))

#Sort a 1D array:-
array=random.randint(1,20,10)
print(array)
array=sort(array)
print(array,'\n')

#Sorting a 2D array:-
array=random.randint(1,20,(3,3))
print(array,"\n")

#Sorts row wise because by default axis=1
array=sort(array)
print(array,"\n")

#Sorts column wise because we set axis=0
array=sort(array, axis=0)
print(array,'\n')

[17 16  1  8 18  4  1  2  7  5]
[ 1  1  2  4  5  7  8 16 17 18] 

[[ 9  9  8]
 [ 8  7 13]
 [ 5 14 10]] 

[[ 8  9  9]
 [ 7  8 13]
 [ 5 10 14]] 

[[ 5  8  9]
 [ 7  9 13]
 [ 8 10 14]] 



# Indexing a numpy array

In [14]:
import numpy as np

array=np.arange(0,11)
print(array)

#Enter the index of the array you want
print(array[4])

#Negative Index number
print(array[-2],"\n")    

#2D Numpy array
array=np.array([[0,1,2],
                [3,4,5],
                [6,7,8]])
print(array)

#Enter the index of the array you want
print(array[0][1])

#Negative Index number
print(array[-1][-1]) 

#Using negative as well as positive index num
print(array[-2][2],"\n") 

#negative index start from right to left, i.e. right most element is -

[ 0  1  2  3  4  5  6  7  8  9 10]
4
9 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
8
5 



# Slicing a numpy array

In [6]:
#1D Array
#(start{inclusive}, stop{exclusive}, step)

import numpy as np

array=np.arange(0,11)
print(array,"\n")

#Start& End both defined
print(array[2:6],"\n")

#End at the end
print(array[2:],"\n")

#End at the end
print(array[2::2],"\n")

#Start from start
print(array[:7:3],"\n")

#IMP
#Copy an array
arrayCopy=array.copy()
print(arrayCopy)

arrayCopy[:]=0

print(arrayCopy)

[ 0  1  2  3  4  5  6  7  8  9 10] 

[2 3 4 5] 

[ 2  3  4  5  6  7  8  9 10] 

[ 2  4  6  8 10] 

[0 3 6] 

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 0 0 0 0 0 0 0 0 0 0]


In [9]:
#2D Array

import numpy as np

array=np.arange(30).reshape(6,5)
print(array,"\n")

#Selecting a row
#Row number defined with or without empty colons=whole row
print(array[2,:])
print(array[2,],"\n")

#Selecting a column
print(array[:,2],"\n")   #EMPTY COLONS GET THE WHOLE ROWS

#Selecting rows+columns
print(array[1:4,0:3],"\n")
print(array[0::2,0::2],"\n")
#array(RowStart:RowStop,ColumnStart:ColumnStop)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

[10 11 12 13 14]
[10 11 12 13 14] 

[ 2  7 12 17 22 27] 

[[ 5  6  7]
 [10 11 12]
 [15 16 17]] 

[[ 0  2  4]
 [10 12 14]
 [20 22 24]] 



# Assigning value to an index in an Array

In [5]:
#1D Array:-

import numpy as np

array = np.array([1,2,3,3,5,6,7,8,9])
print(array)
#Assign value to a single index in an array
array[3]=4
print(array,"\n")

array = np.array([1,2,3,3,5,5,5,5,5])
print(array)
#Assign value to multiple index in an array
array[3:]=4,5,6,7,8,9
print(array,"\n")

array = np.array([1,2,3,3,5,5,5,5,5])
print(array)
#Assign same value to multiple index in an array
array[:]=0
print(array,"\n")

[1 2 3 3 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9] 

[1 2 3 3 5 5 5 5 5]
[1 2 3 4 5 6 7 8 9] 

[1 2 3 3 5 5 5 5 5]
[0 0 0 0 0 0 0 0 0] 



In [18]:
#2D Array:-

import numpy as np

array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(array)

#Assign a value to a single index
array[1][1]=0
print(array,"\n")

#Assign same value to multiple index
array[0:3,1:2]=0
print(array,"\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 0 6]
 [7 8 9]] 

[[1 0 3]
 [4 0 6]
 [7 0 9]] 



# Fancy Indexing

In [1]:
#1D Array

import numpy as np

array=np.arange(0,55,5)
print(array)
index=[0,5,10]

#Create a new array of all the index whose value you want and access them using the array
print(array[index])

[ 0  5 10 15 20 25 30 35 40 45 50]
[ 0 25 50]


In [29]:
#2D Array

import numpy as np

array=np.zeros((10,10),dtype="int")
print(array,"\n")

print(array.shape)
row=array.shape[0]
print(row)

#IMP
#Assigns i(value) to the whole array[i](th)row
for i in range(row):
    array[i]=i
print(array,"\n")

index=[1,3,5,7]
print(array[index],"\n")

#IMP
#Acessing multiple index at the same time
row=[0,1,2,3]
cols=[3,2,0,2]
print(array[row, cols],"\n")

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] 

(10, 10)
10
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]] 

[[1 1 1 1 1 1 1 1 1 1]
 [3 3 3 3 3 3 3 3 3 3]
 [5 5 5 5 5 5 5 5 5 5]
 [7 7 7 7 7 7 7 7 7 7]] 

[0 1 2 3] 



array([0, 3])

# Combining Fancy Indexing with Normal Indexing

In [39]:
import numpy as np

array=np.arange(0,16).reshape(4,4)
print(array)

#Accessing two elements in different coloumns but same rows
print(array[1,[1,3]])
#          1xn   n

#Accessing two elements in different rows but same columns
print(array[[0,2],1])
#              n ,nx1
#Why prints 1 but not 2?

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[5 7]
[1 9]


# Operatons in NumPy lib

In [15]:
#>,<,== operator
import numpy as np

array=np.arange(0,10)
print(array)

print(array>5)

print(array[array>5])

condition = array<=5
print(array[condition])

newCondition = (array!=8) &  (array>=6)
print(array[newCondition])

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[6 7 8 9]
[0 1 2 3 4 5]
[6 7 9]


# Arithemetic Operations


In [28]:
import numpy as np

array=np.arange(0,10,dtype="int")
print(array)

array=array+5
print(array)

array=(((array*10)+20)/5)
print(array)

#Multiplying an array with an array
array=array*array
print(array)

#Exponent
array=array**2
print(array)

#Mode
array=array%2
print(array)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
[ 196.  256.  324.  400.  484.  576.  676.  784.  900. 1024.]
[  38416.   65536.  104976.  160000.  234256.  331776.  456976.  614656.
  810000. 1048576.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [45]:
import numpy as np

array=np.arange(0,10,dtype="int")
print(array)

#Addition
array=np.add(array,5)
print(array)

#Subtraction
array=np.subtract(array,5)
print(array)

#Multiplication
array=np.multiply(array,5)
print(array)

#Division
array=np.divide(array,5)
print(array)

#Exponent
array=np.power(array,2)
print(array)

#Square Root
array=np.sqrt(array)
print(array)

#Mode
array=np.mod(array,2)
print(array)

#Trignometric Functions
print(np.cos(90))
print(np.arccos(-1),"\n")

array=np.random.rand(10)
print(array)
#Lograthmic Functions
print(np.log(array))
print(np.log10(array))      #Base can be inserted

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4 5 6 7 8 9]
[ 0  5 10 15 20 25 30 35 40 45]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
-0.4480736161291701
3.141592653589793 

[0.43934254 0.54023367 0.92808244 0.87297935 0.88311106 0.89785119
 0.11918528 0.8715745  0.54265578 0.63741302]
[-0.82247589 -0.61575352 -0.07463472 -0.13584338 -0.12430431 -0.10775094
 -2.12707603 -0.13745393 -0.61128009 -0.45033745]
[-1.18658189 -0.88834455 -0.10767514 -0.19598057 -0.17933321 -0.15545174
 -3.06872204 -0.19830411 -0.88189075 -0.6496996 ]


##### NUMPY OPERATIONS CHEATSHEET

# Statstical Operations

In [14]:
import numpy as np

array=np.arange(1,11)
print(array)

#Gives the sum of all the values present in the array
print(np.sum(array))

#Gives the mean(average) of all the values present in the array
print(np.mean(array))

#Median:The middle element of the array(if total number of elements in array==even then sum of both middle elements/2 else middle element)
print(np.median(array))

#Standard Deviation: Standard deviation is a statistical measure that quantifies the amount of variability or dispersion in a set of data points. In other words, it provides a way to understand how spread out the values in a data set are from the mean (average) value. A higher standard deviation indicates greater variability, while a lower standard deviation indicates that the values are closer to the mean.
#1. Find the mean (average) of the values.
#2. Subtract the mean from each value to get the deviation from the mean.
#3. Square each deviation.
#4. Find the mean of the squared deviations.
#5. Take the square root of the mean of squared deviations to get the standard deviation.
print(np.std(array))

#Variance: Square of the standard deviaion
print(np.var(array))

#Minimum Value present in the array
print(np.min(array))

#Maximum Value present in the array
print(np.max(array))


[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
5.5
2.8722813232690143
8.25
1
10


##### NUMPY STATISTICS CHEATSHEET

# Solving Mathematical Equations

In [23]:
import numpy as np

#X1  + 3X2  = -1
#2X1 - 7X2  = 10

cofficients=np.array([[1,3],[2,-7]])
results=np.array([-1,10])

print(np.linalg.solve(cofficients, results))

[ 1.76923077 -0.92307692]
